name: Sync Fork - main

on:
  schedule:
    - cron: '0 0 * * *' # every day
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          base: arlo-local
          head: arlo-local
